# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.          
image: php:7.1

pipelines:
    branches:
        development-0.0.1:
        - step:
            name: Production
            caches:
                - composer
            script:
            - ssh ubuntu@23.20.179.178 'bash -s' < execute.sh